---

- name: Update apt cache
  yum: update_cache=yes cache_valid_time=3600

- name: Install Apache2 Webserver
  yum: pkg={{ item }} state=installed
  with_items: "{{ httpd_packages }}"
  register: httpd

#- name: enable apache2 mods
#  apache2_module: name={{ item }} state=present
#  with_items: "{{ apache2_modules }}"

- name: restart apache2
  service: name=httpd state=restarted
